<?php

return [
    'allowed_keys' => [
        'club_name',
        'club_logo',
        'promo_video_url',
        'club_location',
        'telegram_user',
        'telegram_chat_id',
        'telegram_bot_token',
        'telegram_shift_notifications',
        'deploy_agent_download_url',
        'deploy_agent_install_args',
        'deploy_agent_sha256',
        'deploy_client_download_url',
        'deploy_client_install_args',
        'deploy_shell_download_url',
        'deploy_shell_install_args',
        'deploy_shell_sha256',
        'shell_autostart_enabled',
        'shell_autostart_path',
        'shell_autostart_args',
        'shell_autostart_scope',
        'shell_replace_explorer_enabled',
        'shell_replace_explorer_path',
        'shell_replace_explorer_args',
        'auto_shift_enabled',
        'auto_shift_opening_cash',
        'auto_shift_slots',
    ],
    'update_rules' => [
        'club_name' => ['nullable', 'string', 'max:120'],
        'club_logo' => ['nullable', 'string', 'max:2000000'],
        'promo_video_url' => ['nullable', 'string', 'max:1000', 'url'],
        'club_location' => ['nullable', 'array'],
        'club_location.lat' => ['nullable', 'numeric', 'between:-90,90'],
        'club_location.lng' => ['nullable', 'numeric', 'between:-180,180'],
        'club_location.address' => ['nullable', 'string', 'max:255'],
        'telegram_user' => ['nullable', 'string', 'max:120'],
        'telegram_chat_id' => ['nullable', 'string', 'max:120'],
        'telegram_bot_token' => ['nullable', 'string', 'max:255'],
        'telegram_shift_notifications' => ['nullable', 'boolean'],
        'deploy_agent_download_url' => ['nullable', 'string', 'max:500', 'url'],
        'deploy_agent_install_args' => ['nullable', 'string', 'max:1000'],
        'deploy_agent_sha256' => ['nullable', 'string', 'max:128'],
        'deploy_client_download_url' => ['nullable', 'string', 'max:500', 'url'],
        'deploy_client_install_args' => ['nullable', 'string', 'max:1000'],
        'deploy_shell_download_url' => ['nullable', 'string', 'max:500', 'url'],
        'deploy_shell_install_args' => ['nullable', 'string', 'max:1000'],
        'deploy_shell_sha256' => ['nullable', 'string', 'max:128'],
        'shell_autostart_enabled' => ['nullable', 'boolean'],
        'shell_autostart_path' => ['nullable', 'string', 'max:500'],
        'shell_autostart_args' => ['nullable', 'string', 'max:500'],
        'shell_autostart_scope' => ['nullable', 'in:user,machine'],
        'shell_replace_explorer_enabled' => ['nullable', 'boolean'],
        'shell_replace_explorer_path' => ['nullable', 'string', 'max:500'],
        'shell_replace_explorer_args' => ['nullable', 'string', 'max:500'],
        'auto_shift_enabled' => ['nullable', 'boolean'],
        'auto_shift_opening_cash' => ['nullable', 'integer', 'min:0'],
        'auto_shift_slots' => ['nullable', 'array', 'max:6'],
        'auto_shift_slots.*.start' => ['required', 'date_format:H:i'],
        'auto_shift_slots.*.end' => ['required', 'date_format:H:i'],
        'auto_shift_slots.*.label' => ['nullable', 'string', 'max:80'],
    ],
    'defaults' => [
        'deploy_agent_download_url' => '',
        'deploy_agent_install_args' => '--install SERVER_URL="{SERVER}" PAIR_CODE="{PAIR_CODE}"',
        'deploy_agent_sha256' => '',
        'deploy_client_download_url' => '',
        'deploy_client_install_args' => 'SERVER_URL="{SERVER}" PAIR_CODE="{PAIR_CODE}" AGENT_URL="{AGENT_URL}" SHELL_URL="{SHELL_URL}" AUTOSTART={AUTOSTART} AUTOSTART_PATH="{AUTOSTART_PATH}" AUTOSTART_ARGS="{AUTOSTART_ARGS}" AUTOSTART_SCOPE="{AUTOSTART_SCOPE}" REPLACE_SHELL={REPLACE_SHELL} REPLACE_SHELL_PATH="{REPLACE_SHELL_PATH}" REPLACE_SHELL_ARGS="{REPLACE_SHELL_ARGS}"',
        'deploy_shell_download_url' => '',
        'deploy_shell_install_args' => '/quiet SERVER_URL="{SERVER}"',
        'deploy_shell_sha256' => '',
        'shell_autostart_enabled' => false,
        'shell_autostart_path' => '',
        'shell_autostart_args' => '',
        'shell_autostart_scope' => 'machine',
        'shell_replace_explorer_enabled' => false,
        'shell_replace_explorer_path' => '',
        'shell_replace_explorer_args' => '',
    ],
];
